# Generated by Django 4.2.20 on 2025-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marvel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("character", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titile", models.CharField(max_length=100)),
                ("release_year", models.IntegerField()),
                ("image", models.ImageField(upload_to="images")),
                (
                    "actors",
                    models.ManyToManyField(related_name="movies", to="marvel.actor"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Avenger",
        ),
    ]
