# Generated by Django 4.2.20 on 2025-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marvel", "0003_rename_titile_movie_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="image",
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                null=True, related_name="movies", to="marvel.actor"
            ),
        ),
    ]
