# Generated by Django 4.2.20 on 2025-04-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marvel", "0002_actor_movie_delete_avenger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="titile",
            new_name="title",
        ),
    ]
